### PR TITLE
switch from [ContributorsFromGit] to [Git::Contributors]

### PR DESCRIPTION
**Pull request by karenetheridge**
It has fewer dependencies (for #24), and does not have test failure issues.

cc @dolmen

### CODE REVIEW

**Comment by miyagawa** [comment]
This apparently breaks `milla new` because the git command dies with:

```
➜  apVfNCvfk  milla new XYZ
[DZ] making target dir /private/tmp/apVfNCvfk/XYZ
[DZ] writing files to /private/tmp/apVfNCvfk/XYZ
[Git::Init] Initializing a new git repository in /private/tmp/apVfNCvfk/XYZ
[Milla::FirstBuild] Running the initial build & clean
[@Milla/NameFromDirectory] guessing your distribution name is XYZ
[DZ] beginning to build XYZ
[DZ] guessing dist's main_module is lib/XYZ.pm
[@Milla/LicenseFromModule] guessing from lib/XYZ.pm, License is Software::License::Perl_5
[@Milla/LicenseFromModule] Copyright 2015- Tatsuhiko Miyagawa <miyagawa@bulknews.net>
[@Milla/VersionFromModule] dist version 0.01 (from lib/XYZ.pm)
[@Milla/ExtraTests] rewriting release test xt/release/pod-syntax.t
[@Milla/Prereqs::FromCPANfile] Parsing 'cpanfile' to extract prereqs
[@Milla/GithubMeta] A remote named 'origin' was specified, but does not appear to exist.
[@Milla/GithubMeta] skipping meta.resources.repository creation
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by miyagawa** [comment]
I bet it's because the first build runs after `git init` but before the first `git commit`.

**Comment by karenetheridge** [comment]
> I bet it's because the first build runs after git init but before the first git commit.

That sounds right. 

The `milla` command does not come from your distribution, correct?
I thought I had a check in the plugin to do nothing if we were not in a git repository, but I can add a more robust check and then resubmit the patch.

**Comment by miyagawa** [comment]
`milla` is included in this distribution as a wrapper for `dzil`.

**Pull request merged**
